- name: Create a director server instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: aghosh
    instance_type: c3.large
    security_group: sg-c4a4e0a0
    image: ami-108ab142
    region: ap-southeast-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "aghosh"
         group: "aghosh-scg"
         instance_type: "c3.large"
         image: "ami-108ab142"
         wait: true
         region: "ap-southeast-1"
         vpc_subnet_id: subnet-c329fea7
         assign_public_ip: yes
         instance_tags: {"owner":"aghosh"}
         
      register: ec2
    - name: Add new instance to host group
      add_host: hostname="{{ item.public_ip }}" groupname=launched
      with_items: ec2.instances
    - name: Wait for SSH to come up
      wait_for: host="{{ item.public_dns_name }}" port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances
 
- name: Transfer the script
  hosts: launched # This uses the hosts that we put into the in-memory hosts repository with the add_host module.
  sudo: yes # On EC2 nodes, this is automatically passwordless. 
  remote_user: ec2-user # This is the username for all ubuntu images, rather than root, or something weird.
  gather_facts: True  #We need to re-enable this, as we turned it off earlier.
 
  tasks:
  
      - name : Get Wget
        yum: name=wget state=present
     
      - name: Transfer the script
        copy: src=setuprepo.sh dest=/tmp/setuprepo.sh mode=0777

      - name: Execute the script
        command: sh /tmp/setuprepo.sh
 
      - name : Install server
        yum : name=cloudera-director-server state=present
      - name : Install client      
        yum : name=cloudera-director-client
      - name : start server
        service : name=cloudera-director-server state=started