- name: Create a director server instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ lookup('ini', 'key_name section=director file=director.ini') }}"
         group: "{{ lookup('ini', 'security_group section=director file=director.ini') }}"
         instance_type: "{{ lookup('ini', 'instance_type section=director  file=director.ini') }}"
         image: "{{ lookup('ini', 'image section=director file=director.ini') }}"
         wait: true
         region: "{{ lookup('ini', 'region  section=director file=director.ini') }}"
         vpc_subnet_id: "{{ lookup('ini', 'vpc_subnet_id  section=director file=director.ini') }}"
         assign_public_ip: yes
         instance_tags: "{{ lookup('ini', 'instance_tags section=director file=director.ini') }}"
         
      register: ec2
    - name: Add new instance to host group
      add_host: hostname="{{ item.public_ip }}" groupname=launched
      with_items: ec2.instances
    - name: Wait for SSH to come up
      wait_for: host="{{ item.public_dns_name }}" port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances
 
- name: Transfer the script
  hosts: launched # This uses the hosts that we put into the in-memory hosts repository with the add_host module.
  sudo: yes # On EC2 nodes, this is automatically passwordless. 
  remote_user: ec2-user # This is the username for all ubuntu images, rather than root, or something weird.
  gather_facts: True  #We need to re-enable this, as we turned it off earlier.
 
  tasks:
  
      - name : Get Wget
        yum: name=wget state=present
     
      - name: Transfer the script
        copy: src=setuprepo.sh dest=/tmp/setuprepo.sh mode=0777

      - name: Execute the script
        command: sh /tmp/setuprepo.sh
 
      - name : Install cloudera  director server
        yum : name=cloudera-director-server state=present
      - name : Install cloudera director client      
        yum : name=cloudera-director-client
      - name : start server
        service : name=cloudera-director-server state=started